### ISSUE TITLE
Private vs Public buses

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#107]
right now we have public buses that are publicly listed on the current trips page.

if we want to make private buses we need to add some other barrier so that anyone with the link can't buy a ticket. This could be

- a password
- a requirement for the organizer to :+1: or :-1: different reservations

I'd rather go with a password

**Comment by markstm17** [comment]
Or just remove them from the current trips page? If we make it private, we don't allow those trips to be searchable on that page at all. You can't access it unless you have the unique URL.

This means that the organizer texts, emails or inboxes their friends/family/people for that private bus after it has been approved and after the organizer himself or herself receives the link

**Comment by markstm17** [comment]
I'm not against a password, and having everything on current trips, but there will be a point in time when there are 20 buses currently going on the current trips page. There will also be a point in time farther down the road when there will be 100 buses currently on the current trips page. We want to make it as easy as possible for the users to pledge, we don't want them searching for their private bus on a list full of private buses that are current trips. 

Why not skip that process and just have a unique URL? Thoughts @duncangraham ?

**Comment by freindst** [comment]
Here are my opinions:
 1. first of all, hidden url cannot prevent user from getting into the private bus page. My suggestion is password is a must to have private bus.
 2. Second, in trip list, we can have a tab/checkbox to switch on/off listing private bus. A private bus will have a "locked" icon or tag in order to be distinguished from a public bus.
 3. Third, no matter private bus or public bus, organizer or common user both can use url link to invite friends to join in.

**Comment by duncangraham** [comment]
private buses are shipped. We're going with no password as of now. The trip won't appear anywhere, and the organizer/passengers can share the link with friends to spread the word.
