### ISSUE TITLE
Clean up fee

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#115]
many buses have a clean up fee if people spill drink, food, or vom. Let's use this ticket to discuss strategies for how to handle this process and make it as easy as possible to take care of.

For now, there are other priorities, so I'm going to punt this into the nice-to-haves milestone till we get some time to dedicate to it.

**Comment by markstm17** [comment]
Give option to Trip Creator/Organizer to do one of two things:

Have this $100 cost (or whatever industry average cost is-just my experience with First Student) imbedded into the overall cost or cost per person from the beginning. If there is no clean up fee credit the $100 back to the group of customers (20 people all get $5, 50 people all get $2) with an awesome fun email saying something like "You sure made the bus drivers night by keeping the bus clean! We look forward to handling all your fun transportation needs in the future!"


Or


Communicating that there is no "security deposit" charge, but telling the group via email (and eventually from the drivers themselves) that if it isn't cleaned up there will be an additional charge after the fact to everyone (since we have their CC on file) if the bus is left messy or if there are lots of clean up fees. Communicating that it will be spread evenly amongst the group will be huge. Then people can police each other if it's worth not getting charged additionally



---Eventually it will become industry standard that through Argo trips the bus driver makes a 60-90 second announcement before the bus leaves about safety, cleanliness, etc... just like when flying when they show how to put a seatbelt on, etc...

**Comment by duncangraham** [comment]
I think this should be democratized. It's likely that one person could be the cause of the mess, but if more than one person are the cause of it then its a headache for us to charge the responsible parties.

1. cleaning fee will be automatically distributed between all tickets.
2. if a cleaning happens, then we use the cash that people already paid
3. if a cleaning doesn't happen, we give people a $5 credit to use on their next bus.

we could lose money on this, but it'll be a good learning experience.

if you are :+1: on this @markstm17 then I'll get a plan for implementing

**Comment by markstm17** [comment]
@duncangraham I think this is the best way to test this. We need to make sure to communicate this to all of our users, but I like the approach. 

(Same as a security deposit for 1st months rent for apartments/with landlords. At end of the year if nothing is broken or destroyed, responsible tenants get money back, if not they pay. Same concept except it's a lot less money per person and the group component (15-50+ people) make it more complex)

By getting money up front as you said, we have leverage and we don't need to chase when things don't go right. And when the group leaves a clean bus, then we credit them $X.

:+1:

**Comment by duncangraham** [comment]
punting on this till higher priority tickets get completed

**Comment by markstm17** [comment]
That's fine @duncangraham. When we do buses I can just include the cost of a service or clean up fee expecting that it will happen. If it doesn't, an extra $X in our pocket and in the future we can work on crediting the groups that keep things clean

**Comment by markstm17** [comment]
For now I'm going to close this ticket @duncangraham (Please reopen if you think it is essential, but I think there are other higher priority things right now for us and on the product side)

Reason is the following:
- We will embed the $100 cost for food/drink with the button you created (That **does need** to be accounted for in the price estimator #167) for every bus where they bring food and drink
 - If they say they aren't bringing food and drink, but they do after the fact, then we charge them accordingly
- We will have our customers Credit Card information in case there are problems and we need to charge different groups **after the fact** 

# In Future
- Charge an additional refundable $100 "Security Deposit" that will be credited back to group if bus is not left messy, nobody pukes, etc...
