### ISSUE TITLE
Expiration Date for Credit Card problems

### ISSUE THREAD

**Issue by markstm17** [ArgoBus/Argo-Project-V0#138]
I know we have MM/YYYY

But let's consider changing it to MM/YY instead 

I have had a few people confused and stuck on that page because of that

**Comment by duncangraham** [comment]
this is more an issue of ineffective communication. once I add the [card.js code](https://jessepollak.github.io/card/) it should be resolved though.

**Comment by markstm17** [comment]
We haven't tested this/done another bus through Argo since Buffett. 

Is the card.js code added? Should we test it @duncangraham so we can see if we can close this ticket?

**Comment by duncangraham** [comment]
with card.js and nod.js this shouldn't be an issue anymore. the layout is much more clear, and the error messaging should help as well.

### Here's what happens if you fuck up the year:

<img width="1390" alt="screen shot 2015-10-01 at 12 34 47 pm" src="https://cloud.githubusercontent.com/assets/865298/10231659/d41077e4-6838-11e5-81c0-f7d746776b52.png">
