### ISSUE TITLE
Not confirmed reservation flow

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#166]
We should change the functionality around 'This trip has not been confirmed by argobus.com yet. Please check later.'

I think visually that we should have a status tracker of the trip. 

## status
1. Booking a bus, pledge now
2. Bus Booked, pledge to get a minimum of 10 riders
3. 10 riders going! Share with friends to drop the price and get discounts.
4. Threshold reached! Bus price decreases. Share to get 100% booked! (what incentive for 100% booked?)
5. 100% booked, charge for trip 24 hours prior
6. Trip charged
7. Trip completed

**Comment by markstm17** [comment]
This was something I was going to bring up as we continue to start to book more and more buses through Argo, glad you brought it up.

## Initial reaction
--
- With your 7 step process above do you envision that for both public and private buses? I see it only as public. 

- I don't like the use or wordage of "Booking a bus" in step 1, and step 2, and then in step 4 saying the "threshold is reached" When the threshold is reached it goes from "Potential" bus to "Booked" bus. Some ideas to replace booked for Steps 1 and 2 include
 - Bus is...
  - Reserved 
  - Ordered
  - In the pipeline
  - Available 
  - Free

- Whenever it gets 100% booked (whether it is 2 weeks in advance or 30 minutes before bus leaves), then cards of all the "Argoers" (I like that a lot!) get charged. Otherwise if it is not 100% booked, then every card gets charged at the departure time of the bus (to allow more and more people to come last minute if there are available seats)

**Comment by markstm17** [comment]
How important do you think this is with the other priorities right now @duncangraham ?

**Comment by duncangraham** [comment]
It seems like this has been done, since all buses are now live by default
