### ISSUE TITLE
Price estimator

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#167]
I don't want to have to wait for a charter company to get back to us with a potential quote. I want to dynamically generate pricing estimates based on size/type/trip duration/miles travelled.

@markstm17 this is where your industry experience comes in. I need a few simple rules that I can use to write an algorithm to make a loose estimate. So, whats the simplest way to generate a loose estimate? I don't want to use more than 2 (maybe 3) variables.

## some rough frameworks
- if bus costs are largely derived from time spent, then lets go with that
- if bus costs are largely derived from distance traveled, then lets go with that
- we can also do a more complicated combination of the two

## next steps
@markstm17 provides input. Then, with a framework, I'll post a plan for implementation

**Comment by markstm17** [comment]
For First Student specifically, we can do $50 hourly rate with a fee of $100 for food and beverage, they are charging it on all trips now assuming there will be food/bev.

So for our cost the equation would be 50x + 100 for our price estimator for anything yellow school bus related **(in the midwest)** Then we would add the multiplier based on the amount of pledges. 

--

It changes in CA and on the West and East coast because of standard of living and general costs. The few quotes I've done in SF its closer to $85-$100 per hour (Our cost for Eric's 49ers and Falcons game was $1,012.75 for 10 hours. 


Does that provide a good enough start @duncangraham with where we are at, especially with still using and working with First Student for basic transit needs? 

I'll continue to explore and work around with more motor coach companies, but from calling and emailing around for Eric the last two days, they range from $1,305-$2,400 for a 10 hour rental period for the 49ers and Falcons game as one specific example. That means it's $130-$240 per hour which is a big range. With that being said there was only one company at $2,400, the next closest was $2,000 (so $130-$200 per hour). The $2,400 quote was the Uber LUX of charter companies; Executive Charters. 

Either way it is a much greater difference that what I know and have built in with First Student for a $40-$50 hourly rate (plus food/bev fee)

**Comment by duncangraham** [comment]
This is how I think the algorithm will work. I've written clear names and comments so you should be able to read and understand the code with minimal effort @markstm17 

```
// all the variables we need
// variables that don't have set values are empty for now
var hourlyRate;
var tripDuration;
var argoMultiplier = 1.25; // midpoint of range [1, 1.5] which is fine for an estimate
var foodAndDrink = 100;
var costEstimate;

// test for coastal cities/higher hourly rate.
// test if the city is near coastal latitudes (this isn't the best solution)
if ( city >= westLat || city <= eastLat ) { 
  hourlyRate = 90; // midpoint of [80, 100] range
}
// non-coastal city
else {
  hourlyRate = 50;
}

// set the estimate
costEstimate = (hourlyRate * tripDuration) * argoMultiplier + foodAndDrink;

**Comment by markstm17** [comment]
@duncangraham makes sense, I think that will be great to start trying out. 

# To answer your question
> Would Chicago (a large non-coastal city) have higher rates?
I think so. There is definitely a component to standard of living and the area that you live in. I know that Ray Land (In our recruits page) would have a better idea of that-at least for motor coaches with his in depth industry knowledge. 

# One Question
Don't we want to multiply the argoMultiplier by the entire total cost?
- ((hourlyRate*tripDuration)+foodAndDrink)*argoMultiplier

# One Comment 
The hourly rate of $90 for "coastal cities" is based upon my knowledge for getting 4-5 quotes from **First Student**. As far as motor coaches the price obviously goes up.

**Comment by duncangraham** [comment]
<img width="1389" alt="screen shot 2015-10-07 at 10 19 23 pm" src="https://cloud.githubusercontent.com/assets/865298/10358298/8e1cbe4c-6d41-11e5-8041-a056fe886172.png">

this is working now (minus the big city multiplier)!

Now I need to figure out how this price interacts with the templates. I'm realizing that I should be able to make templates on the fly, based on parameters provided.

--

## questions

### 1
lets say there's a bus with an estimated price of $800

do we green light the bus go with **10 passengers @ $80**? 
or **16 people @ $50 a ticket**? Why?

after the bus is a go, when do the price changes occur? Why?

### 2
what do the templates (green lit bus and price changes) look like for the smaller and larger sizes?

would love to hear your thoughts @markstm17

**Comment by markstm17** [comment]
> do we green light the bus go with 10 passengers @ $80? 
> or 16 people @ $50 a ticket? Why?

To answer the above question (with how I envision it) I'm going to use a quick analogy. We both go into Subway to get a sub. @duncangraham and trevor both get a Sweet Onion Chicken Teriyaki sub. BUT Dunc only gets lettuce and tomato while Trevor puts EVERYTHING on his sub (olives, green peppers, pickles, the works, etc..) As we both know this is called **customization**, and with different trips, organizers, activities, etc that is how all trips are. We need to allow the ORGANIZER to CHOOSE the Threshold.

The Price estimator and being able to Auto generate the quotes is **RAD,** and a great step, but it's still a baby step in this entire visual process. 

Instead of showing $800 (on your example above) I think it should do the following:
- Spit out our price-o-meter #135, giving the organizer the ability to forecast/gauge what the cost per person will be at different capacity levels #184 
- The Organizer then **ENTERS** a threshold before submitting (Subject to change/edit as the trip progresses)
 - For the time being we can suggest to get a minimum of 20 people or under $40 per person (I can explain why I picked those numbers if you want)
- Then over time, as people pledge, the price-o-meter is in the "red" until the threshold is hit. Once it is hit, it shows the maximum of what people would pay (Threshold), what people are currently paying and what the cheapest cost per person could be if bus is at capacity. 

**But as an organizer of a bus, or a person pledging for a bus, you don't see the actual cost of the bus. You see the breakdown with more and more people through #184, whether it's for a private or public bus**



> what do the templates (green lit bus and price changes) look like for the smaller and larger sizes?

We are currently working templates, because that's what Blade made and we used for our first two buses for Buffett. We need to switch over to our revenue multiplier #178 and #179 (I'll make a specific ticket for Template vs Multiplier too)

Imbedded in the price-o-meter #135, and the cost per person simulator #184 as more and more people pledge for the bus, is Argo's cut/revenue through our bus multiplier. 
- Your $800 example above (for a 50 person school bus) goes as follows:
 - 10% at 10 people ($880 or $88 per person)
 - 20% at 20 people ($960 or $48 per person)
 - 30% at 30 people ($1040 or $35 per person)
 - 40% at 40 people ($1120 or $28 per person)
 - 50% at 50 people (full capacity) is ($24 per person)

When you say smaller/larger bus (Above question) do you mean total capacity on the bus (seats) or smaller or larger size groups/trips of people? 

As far as my opinion about **our multiplier, which have a direct impact on Argo's revenue** it should be at the different % capacities, like above, regardless of the size of the vehicle/however many seats there are. (20%, 40%, 60%, 80%, 100%, and throughout for private events) 
- As far as when perceived value occurs for public buses, it COULD be at 70% capacity (35 people) for example, I am just using those numbers above to get point across. 



This is a lot of information @duncangraham, read it over a few times when you get up and let me know your thoughts, if you have questions, etc...

This process is going to be a value differentiator, because it hasn't been done like this before. Rally Bus, Tailbus, current bus companies, bars that organize buses, the old process etc... don't allow
- Organizers to set thresholds
- Decrease the price dynamically with private or public trips 
- Show the price-o-meter for when the cost per person will decrease

**Comment by duncangraham** [comment]
@markstm17 could you look at https://github.com/ArgoBus/Argo-Project-V0/issues/167#issuecomment-146552486?

is that relevant anymore? If not, then lets close this ticket. The estimator has been built and will ship in #226 

# visual
<img width="1391" alt="screen shot 2015-10-16 at 12 37 59 pm" src="https://github-cloud.s3.amazonaws.com/assets/865298/10566199/f37186fa-7594-11e5-9e6b-d7a212adc339.png">

**Comment by markstm17** [comment]
@duncangraham  the estimated ticket range is exactly what we want on this page (versus old flat fee price)

Double thumbs up.


So we are on the same page Dunc, when a new bus is created (Green button is clicked by organizer), then we get a new screen with our #135 (or your screenshot below of the $50-$10 POM) as more and more pledges sign up

![12177768_10154274292717598_1290140938_n](https://cloud.githubusercontent.com/assets/11848699/10624256/47b78304-775c-11e5-9f17-b8402e5a204b.jpg)

**Comment by duncangraham** [comment]
yea exactly. closing this for now since all the work associated with it has been done.
