### ISSUE TITLE
if you're one of the first 5 people to join you get a free ticket

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#206]
We need to reward early adopters as much as fucking possible.

**Comment by markstm17** [comment]
Lets think and brainstorm here right now:

- How hard will that be to implement on top of what I need for #207 ?
- If there is a group of 6-12 friends (as an example) then does someone or multiple people feel screwed or taken advantage of and not like that a few of them got to go for free? (or it could make them what to be the first 5 to sign up in the future)
- I'm assuming this is only for public buses and the public bus flow (for this incentive) Is that correct from your initial thoughts/post? 

# My Thoughts 
My thought process **down the road** is that the first 5-10 people of every bus will get double points (or double buses) **I say down the road because there are currently more important things to do and build with #189 **
- When an "Argoer" pledges and attends 5 different trips, then the 6th is free (These numbers can change and also be tested)
- But **EVERY TIME** you're part of the first 5-10 people to pledge, you get to account that one trip as two trips on the "incentive for free bus trip meter"
 - This, along with the birthday incentive, in my opinion will get more and more people to sign up the same way that I currently do with Subway wanting free subs through their rewards program

**Comment by markstm17** [comment]
Let's make this as simple as possible @duncangraham 

I just mentioned it in https://github.com/ArgoBus/Business/issues/14

Lets implement these three incentives ASAP, right when you launch the new version this weekend or next week with postgres #240 

# Incentives
- Free birthday month
 - I'm fine with the first 5 people who go are free (Realize that these 5 people may be from the same sub group of people)
- Every 5 buses, 6th is free
- Dynamic Pricing where more people who sign up, cheaper and cheaper it gets

**Comment by duncangraham** [comment]
I now disagree with implementing this. Giving away free tickets is not the goal: rewarding people for getting friends/acquaintances to join should be the goal.

With that in mind, I think if you buy X many tickets for friends, you should get yours for free. If you invite X many friends that join the trip, your ticket should be free. That's out of scope for this ticket though.

**Comment by markstm17** [comment]
Agree with both comments @duncangraham
