### ISSUE TITLE
Switch off of MySQL to something else

### ISSUE THREAD

**Issue by duncangraham** [ArgoBus/Argo-Project-V0#240]
Meeting with @nickyj88 sometime next week to get things moving!

**Comment by duncangraham** [comment]
just talked to zain and he recommended a totally different approach (with his experience I'd be more compelled to go with his take).

He thinks we should switch off of mysql and move to postgres which has better datatypes for our needs (times, geo points, etc). supposedly it has fewer idiosyncrasies than mysql as well.

He recommended breaking things down into 4 tables.

1. Trips
2. Waypoints (the pickup/dropoff/intermediate locations on a trip)
3. Users
4. Events (trips would be associated with these)

**Comment by markstm17** [comment]
What was your friend Nick's recommendation @duncangraham ?? (Out of curiosity) 

And has Zain used postgres before?? (with his experience at Lovely and in general) 

It sounds (based on what you've said above) Zain's recommendation should maybe be the route we go. You're much more the expert with this stuff then I am so just keep me in the loop as you figure that side of what we are doing out. It's essential for Argo! Woohoo!

**Comment by duncangraham** [comment]
Zains super knowledgeable about postgres (and databases in general).

Nick recommended using neo4j (http://neo4j.com/developer/guide-data-modeling/), which he said is, 'the most artistic way to represent data'. It sounds really cool, but goes against this http://mcfunley.com/choose-boring-technology. 

(That article is the reason I pulled us off Parse initially)

gonna sit down with either zain or nick and have them help me with the schema (https://en.m.wikipedia.org/wiki/Database_schema)

**Comment by markstm17** [comment]
Alright, great. Really interested to hear more about what Zain says when you talk with him more this week

**Comment by duncangraham** [comment]
# tables 

all tables will have an id, createdAt, and updatedAt columns, so I've left them out. This is how the data will be arranged. I've planned some things in the data that haven't been made in the product, or much talked about. Lemme know if anything is unclear. implementation begins tomorrow!

## trips

id | data type
------------ | -------------
ride_type | TEXT
max_passenger | INT
food_trip | TEXT
estimated_cost | CURRENCY AMOUNT
actual_cost | CURRENCY AMOUNT
is_completed | BOOLEAN
start_point | LAT/LON
start_address | TEXT
end_point | GEOJSON
end_address | TEXT

hasOne Organizer (user)
hasMany Passengers (users)
hasOne Event

## users

id | data type
------------ | -------------
first_name | TEXT
last_name | TEXT
phone | PHONE
customerID | STRIPE
email | EMAIL
hash | HASH
salt | SALT
activation_key | PASSPORT
reset_key | PASSPORT
role | TEXT
birthday | DATE
address | ADDRESS
lon_lat | GEOJSON

hasMany Trips

## events

id | data type
------------ | -------------
first_name | TEXT
date_time_range | DATE TIME RANGE
minimum_age | INT
category | TEXT ARRAY

hasMany Trips

**Comment by markstm17** [comment]
This is great @duncangraham . Giddy with excitement to see how this looks in the next week

**Comment by duncangraham** [comment]
## updates
the database change has been implemented, along with brand-spankin-new models!

# app up and running
<img width="969" alt="screen shot 2015-10-29 at 4 25 03 pm" src="https://cloud.githubusercontent.com/assets/865298/10834914/a048c2c6-7e5a-11e5-97c6-162cd18eed23.png">

# new schema
<img width="1389" alt="screen shot 2015-10-29 at 4 35 34 pm" src="https://cloud.githubusercontent.com/assets/865298/10834967/1b8e79e4-7e5b-11e5-8697-867340b4417c.png">



You'll notice a few changes
1. i've added a referral id and code on the user model
2. I've broken the user location data into more granular pieces
3. I've added organizer associations for events as well as trips. right now the same person will be making both at the same time without realizing there is a split in the data. Eventually though we will aggregate trips around events potentially.

# moving forward
now it's time for the CRUD work => https://en.m.wikipedia.org/wiki/Create,_read,_update_and_delete
I'll need to make create/read/update/delete functions for Trips, Events, and Users.
I should be able to reuse much of the code that we already have, but we'll see

**Comment by duncangraham** [comment]
Saving for later-- I need to make sure that the postgres DB's have PostGIS (http://postgis.net/) enabled

```
CREATE EXTENSION postgis;
```

https://github.com/sequelize/sequelize/pull/4013#issuecomment-120553715

**Comment by duncangraham** [comment]
Users can now be created and updated!

Currently working on trips!

Yay!

**Comment by markstm17** [comment]
WOOHOO!

How are the trips coming along?

Want to go through, play around for bugs and test this tonight @duncangraham ?

**Comment by duncangraham** [comment]
trips are done, and now I'm still working on the trip details page (there will need to be a better trip edit page).

Which brings up an important question (which I know we've discussed before):

## should users be allowed to edit public trips? private trips?
my inclination is that unless its a private trip, users should not be able to edit the trips

**Comment by markstm17** [comment]
### Text message I sent earlier to this

"I'd say NOT RIGHT NOW for public trips. I'd say lets get a viewpoint from bars and get feedback from them and then decide if we want to change that based upon their feedback

But, for private trips, ABSOLUTELY

As we have talked about, Argo is the organizer for public trips; because of the autonomy. For private trips there are still organizers"


### Things to consider @duncangraham 

- How do we truly differentiate and dictate a public vs private trip?
 - This is why it has been tough for me to wrap my head around this concept and distinction. Just because it is leaving from a bar, or a public location, does it automatically make it a public bus? 

## Example

The Packers have 8 home games a year and there may be 25 bars in southeastern Wisconsin that plan on doing all 8 games, while 15 plan on doing 6 games, while 10 plan on doing 4 games, while 15 plan on doing 2, while 17 bars plan on going 1 game a year. What if 6 out of the 82 bars want to do a Halloween bus crawl in 2016 through Argo? It is a bar in a public area that is doing a public bus of Halloween goers. 

## Questions 

How do you envision categorizing the different events? How would you envision Argo automatically knowing what each of those 6 bars wants to do for Halloween? 
- This is where I see bars/managers/owners being organizers for their bar EVEN though it is a public event based upon their event details. 
-Outside of scheduled sports and even scheduled concerts, I see this being a challenge IF WE DON'T ALLOW BARS TO EDIT TRIP DETAILS for events like the "Halloween bus" where the bar may decide after the trip quotation through Argo that they want the bus for an extra hour longer then they originally quoted/anticipated/wanted. 


## Other examples that bars have done and could do
- Brewery Bus Tours
- Tours of the City
- Pub Crawls

 If you want my honest opinion, I think the "mass automation" happens a little farther down the line. After 100's of buses and trips through Argo where we learn. It isn't just gonna happen overnight. 

# We've got to allow bars to suggest different bus trips and I think there needs to be the ability to edit these suggested trips from a bars standpoint, even though they are PUBLIC

**Comment by markstm17** [comment]
Another example is the Brewers schedule of 82 home games.

Realistically (at least initially, and probably forever) **all bars** that use Argo _won't_ be doing **buses for every game**. There are different bars that may want to organize bus trips to different games. We have got to give the bars the ability to plan for their personal location

### Other questions to consider
- What if for a specific game the owner/manager/bartender wants to specifically leave an hour early with whoever pledges for a tailgate because it is a "BIG GAME"
- What if the bar/group plan on tailgating at bar (Because the bar is trying to capitalize on all of those people at their bar up until game time) and leave 30 minutes right before the game?


# Editing for Public buses
- Do you think the inability for a bar to edit a bus that is leaving from their business is a deterrent to them as a location and partner with Argo? 
- Do you think that when a bar would want to change the recommended or automated details, that if they had to get Argo to approve it, it would be a smooth process for our customers/bars?
- Why are we not allowing ANY public buses to be edited by the locations if they are bars/businesses?

**Comment by markstm17** [comment]
# Another Example

#### Edit and changes with different events

It was announced 6 days ago that there was a time change for the Nov 22nd Packers game which would change the details of the trip

![screen shot 2015-11-09 at 12 21 09 am](https://cloud.githubusercontent.com/assets/11848699/11027180/566f3b8c-8678-11e5-8bfb-f825e9c0ecf8.png)
Rally Bus not updating their site (Probably because every single one of their buses has 0 people signed up for the bus)
--

![screen shot 2015-11-09 at 12 23 34 am](https://cloud.githubusercontent.com/assets/11848699/11027186/6ed8ae1a-8678-11e5-93da-dfa43d5eb6e0.png)
--

![screen shot 2015-11-09 at 12 21 36 am](https://cloud.githubusercontent.com/assets/11848699/11027189/758b74a4-8678-11e5-8c62-ac9428549d34.png)

**Comment by markstm17** [comment]
Lastly, some bars and some buses may want to add/change different details

- Some groups or buses may want to stay after the Packers game in Green Bay longer then others for whatever reason
- Some may want to have a stop or two on the way home pending the game time and day of the game
- Some may plan this as entire day event versus transportation to a game

### I'm going to reiterate this; I read this in one of the articles/things you gave me

# You can not completely automate an experience
- This is how we are going to be different then Rally Bus and any other competitor. We are changing the process and automating a ton of aspects, but my gut feeling is that I think we are going to find that our partners are going to want to **HAVE THE ABILITY TO HAVE A LITTLE MORE CONTROL** then complete automation for quote on quote Public Trips based upon scenarios and situations that we can not yet predict

**Comment by markstm17** [comment]
> trips are done, and now I'm still working on the trip details page (there will need to be a better trip edit page).

> Which brings up an important question (which I know we've discussed before):

> ## should users be allowed to edit public trips? private trips?
> my inclination is that unless its a private trip, users should not be able to edit the trips 


Your comment above relates directly to #190

**Comment by markstm17** [comment]
Lastly,

I still **more so** see **Argo Bars** as _Uber Drivers_ or _Airbnb Hosts_

- They may or may not want to do every suggested trip Argo suggests them to "Host" or "Pick Up" pledges from
- Control and flexibility are two of the biggest benefits with our generation, so put yourself in their shoes.  - If you were a bar would you want us Argo to control EVERYTHING about the trip? Would you want the ability to Edit a trip if you wanted or needed too without getting permission or accessibility from someone within Argo? 

## With that being said
- I think there should be recommended trips so that bars don't need to worry about any work, and based off of previous trips we can just plug those in when a bar requests the same as before! 
- This is where we can really leverage the automation behind your vision @duncangraham 


Again, you CAN NOT AUTOMATE EXPERIENCE. The _bars as well as the bus companies_ are going to be the ones that will be providing the "real experience" just like Uber Drivers and Airbnb Hosts do that for riders and travelers.  

# Keep that in mind

**Comment by markstm17** [comment]
# Uber email to a Driver that hasn't driven for a while
### Argo should have something similar for Bars that are signed up through Argo

![12207885_10154314186152598_1736215799_n](https://cloud.githubusercontent.com/assets/11848699/11028205/2948cd62-8682-11e5-956f-411bacfb5893.jpg)

**Comment by duncangraham** [comment]
@markstm17 lets keep comments in line with the original intent of the tickets. This ticket was about switching off of MySQL, which happened. Closing.
